"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# !!!Remember this has to do with CustomManager and CustomUser!!!!
AUTH_USER_MODEL = 'main.CustomUser'  
 

# Quick-start development settings - unsuitable for production
#  See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '25rv1j5k)3589&hz%dv1_ikys+8bo48vhqh=v7op@i8r3u)-1z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'main',
    'checkout',
    'social_auth',
    'registration',
    'crispy_forms',
    'bootstrap3',
    'stripe',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.instagram',
    # allauth.socialaccount.providers.twitter',
    # 'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.stripe',
    
    # 'oauth2_provider',
    #'corsheaders'
 

]
SITE_ID = 1

# CORS_ORIGIN_ALLOW_ALL = True

CRISPY_TEMPLATE_PACK = 'bootstrap3'

ACCOUNT_ACTIVATION_DAYS = 3
REGISTRATION_AUTO_LOGIN = True
# LOGIN_REDIRECT_URL = '/'

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'corsheaders.middleware.CorsMiddleware'
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = (
    
    'social.backends.twitter.TwitterOAuth',
    # # 'social.backends.open_id.OpenIdAuth',
    # 'social.backends.google.GoogleOpenId',
    # 'social.backends.google.GoogleOAuth2',
    # 'social.backends.google.GoogleOAuth',
    # 'social.backends.instagram.InstagramOAuth2',
    # 'social.backends.facebook.FacebookOAuth',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',


 )

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_auth.context_processors.social_auth_by_type_backends',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],

        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'memory_mail',
        'HOST': '127.0.0.1',
        'USER': 'root',
        'PASSWORD': 'root',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# allauth
LOGIN_URL = '/dashboard'
LOGIN_REDIRECT_URL = '/dashboard'

# # ACCOUNT_AUTHENTICATION_METHOD = 'username_email',
# ACCOUNT_CONFIRM_EMAIL_ON_GET = False
# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = LOGIN_URL 
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None

# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
# ACCOUNT_EMAIL_REQUIRED = False
# ACCOUNT_EMAIL_VERIFICATION = None
# ACCOUNT_EMAIL_SUBJECT_PREFIX = 'My Subject:'
# ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'

# ACCOUNT_LOGOUT_ON_GET = False
# ACCOUNT_LOGOUT_REDIRECT_URL = "/"
# ACCOUNT_SIGNUP_FORM_CLASS = None
# ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = True
# ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
# ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

# ACCOUNT_USERNAME_MIN_LENGTH = 1
# ACCOUNT_USERNAME_BLACKLIST = []
# ACCOUNT_USERNAME_REQUIRED = True
# ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = False
# ACCOUNT_PASSWORD_MIN_LENGTH = 6
# ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# ACCOUNT_SESSION_REMEMBER = True

# # SOCIALACCOUNT_QUERY_EMAIL = ACCOUNT_EMAIL_REQUIRED
# # SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIAL_AUTH_DEFAULT_USERNAME = 'new_social_auth_user'

# working :)
SOCIAL_AUTH_TWITTER_KEY = '9rCc3lx8eN6FmPoGWpDWYBUUM' 
SOCIAL_AUTH_TWITTER_SECRET = 'XkQgkmLTA5TJ6jbuGznBjCA4SZPio1zFo6VqcPVmUGN5JAuF51'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '567871385083-sjhepk7nmquvjlcs8rfergf8hl56v90g.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '8h2HilLXMg_nUp8tHhHjM2Ot'

# AIzaSyD8c4MtQrNeoU5I-yeW6KvI9b5W3I5_uRI
# FACEBOOK_APP_ID = '1531820980479355'
# FACEBOOK_API_SECRET = '8b52de7efdde6dcc2c0c7fe10e367286'

# FACEBOOK_EXTENDED_PERMISSIONS = ['email']
  
# TWITTER_CONSUMER_KEY = '9rCc3lx8eN6FmPoGWpDWYBUUM'  
# TWITTER_CONSUMER_SECRET = 'XkQgkmLTA5TJ6jbuGznBjCA4SZPio1zFo6VqcPVmUGN5JAuF51'

# not working :(
SOCIAL_AUTH_INSTAGRAM_KEY = '4a0f126f6ec64c929ad658b899d44252'
SOCIAL_AUTH_INSTAGRAM_SECRET = '187358f9a61841c58cc50461a3f5cb51'

# maybe? :(
# # SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '483252136915-bpa9815e04uc4e3ehg4904osd7q0orva.apps.googleusercontent.com'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'c2dV6qnKTfpTUR5hG3SCJwDs'
# # not
# SOCIAL_AUTH_FACEBOOK_KEY = '1531820980479355'
# SOCIAL_AUTH_FACEBOOK_SECRET = '8b52de7efdde6dcc2c0c7fe10e367286' 

# SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']


# Stripe Stuff

# test keys
STRIPE_PUBLIC_KEY = 'pk_test_abDKoFj8mdk1c2LkW1R21T7k'
STRIPE_SECRET_KEY = 'sk_test_VvkPjFcKvIHib7Yy13ZNdWRi'


# # live keys
# STRIPE_PUBLISHABLE_KEY = ''
# STRIPE_SECRET_KEY = ''
